version: "2"

linters:
  settings:
    goconst:
      ignore-string-values:
        - main
    ireturn:
      allow:
        - error
        - stdlib
        - github.com/gliderlabs/ssh.Signer
        - github.com/go-git/go-git/v6/storage.Storer
  enable:
    - gocritic
    - gocognit
    - gocyclo
    - maintidx
    - dupl
    - mnd
    - unparam
    - ireturn
    - goconst
    - errcheck
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - goconst
          - dupl
          - mnd
          - ireturn
          - unparam
