version: "2"

linters:
  enable:
    - gocritic
    - gocognit
    - gocyclo
    - maintidx
    - dupl
    - mnd
    - unparam
    - ireturn
    - goconst
    - errcheck
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - goconst
          - dupl
          - mnd
          - ireturn
          - unparam
